// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: shared/proto/sensor/sensor.proto

package sensor

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_sensor_sensor_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_sensor_sensor_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{4, 0}
}

// Sensor data message
type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorValue   float64                `protobuf:"fixed64,1,opt,name=sensor_value,json=sensorValue,proto3" json:"sensor_value,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Id1           string                 `protobuf:"bytes,3,opt,name=id1,proto3" json:"id1,omitempty"`
	Id2           int32                  `protobuf:"varint,4,opt,name=id2,proto3" json:"id2,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetSensorValue() float64 {
	if x != nil {
		return x.SensorValue
	}
	return 0
}

func (x *SensorData) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorData) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *SensorData) GetId2() int32 {
	if x != nil {
		return x.Id2
	}
	return 0
}

func (x *SensorData) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Response for sensor data operations
type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *SensorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SensorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SensorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Batch sensor data for bulk operations
type SensorDataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SensorData          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataBatch) Reset() {
	*x = SensorDataBatch{}
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataBatch) ProtoMessage() {}

func (x *SensorDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataBatch.ProtoReflect.Descriptor instead.
func (*SensorDataBatch) Descriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SensorDataBatch) GetData() []*SensorData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=sensor.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_sensor_sensor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_sensor_sensor_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_shared_proto_sensor_sensor_proto protoreflect.FileDescriptor

const file_shared_proto_sensor_sensor_proto_rawDesc = "" +
	"\n" +
	" shared/proto/sensor/sensor.proto\x12\x06sensor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\n" +
	"SensorData\x12!\n" +
	"\fsensor_value\x18\x01 \x01(\x01R\vsensorValue\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03id1\x18\x03 \x01(\tR\x03id1\x12\x10\n" +
	"\x03id2\x18\x04 \x01(\x05R\x03id2\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Z\n" +
	"\x0eSensorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"9\n" +
	"\x0fSensorDataBatch\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.sensor.SensorDataR\x04data\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x94\x01\n" +
	"\x13HealthCheckResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).sensor.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xdd\x01\n" +
	"\rSensorService\x12<\n" +
	"\x0eSendSensorData\x12\x12.sensor.SensorData\x1a\x16.sensor.SensorResponse\x12F\n" +
	"\x13SendSensorDataBatch\x12\x17.sensor.SensorDataBatch\x1a\x16.sensor.SensorResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.sensor.HealthCheckRequest\x1a\x1b.sensor.HealthCheckResponseBAZ?github.com/worlder-team/microservice-server/shared/proto/sensorb\x06proto3"

var (
	file_shared_proto_sensor_sensor_proto_rawDescOnce sync.Once
	file_shared_proto_sensor_sensor_proto_rawDescData []byte
)

func file_shared_proto_sensor_sensor_proto_rawDescGZIP() []byte {
	file_shared_proto_sensor_sensor_proto_rawDescOnce.Do(func() {
		file_shared_proto_sensor_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_sensor_sensor_proto_rawDesc), len(file_shared_proto_sensor_sensor_proto_rawDesc)))
	})
	return file_shared_proto_sensor_sensor_proto_rawDescData
}

var file_shared_proto_sensor_sensor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_sensor_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_sensor_sensor_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: sensor.HealthCheckResponse.ServingStatus
	(*SensorData)(nil),                     // 1: sensor.SensorData
	(*SensorResponse)(nil),                 // 2: sensor.SensorResponse
	(*SensorDataBatch)(nil),                // 3: sensor.SensorDataBatch
	(*HealthCheckRequest)(nil),             // 4: sensor.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 5: sensor.HealthCheckResponse
	(*timestamp.Timestamp)(nil),            // 6: google.protobuf.Timestamp
}
var file_shared_proto_sensor_sensor_proto_depIdxs = []int32{
	6, // 0: sensor.SensorData.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: sensor.SensorDataBatch.data:type_name -> sensor.SensorData
	0, // 2: sensor.HealthCheckResponse.status:type_name -> sensor.HealthCheckResponse.ServingStatus
	1, // 3: sensor.SensorService.SendSensorData:input_type -> sensor.SensorData
	3, // 4: sensor.SensorService.SendSensorDataBatch:input_type -> sensor.SensorDataBatch
	4, // 5: sensor.SensorService.HealthCheck:input_type -> sensor.HealthCheckRequest
	2, // 6: sensor.SensorService.SendSensorData:output_type -> sensor.SensorResponse
	2, // 7: sensor.SensorService.SendSensorDataBatch:output_type -> sensor.SensorResponse
	5, // 8: sensor.SensorService.HealthCheck:output_type -> sensor.HealthCheckResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shared_proto_sensor_sensor_proto_init() }
func file_shared_proto_sensor_sensor_proto_init() {
	if File_shared_proto_sensor_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_sensor_sensor_proto_rawDesc), len(file_shared_proto_sensor_sensor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_sensor_sensor_proto_goTypes,
		DependencyIndexes: file_shared_proto_sensor_sensor_proto_depIdxs,
		EnumInfos:         file_shared_proto_sensor_sensor_proto_enumTypes,
		MessageInfos:      file_shared_proto_sensor_sensor_proto_msgTypes,
	}.Build()
	File_shared_proto_sensor_sensor_proto = out.File
	file_shared_proto_sensor_sensor_proto_goTypes = nil
	file_shared_proto_sensor_sensor_proto_depIdxs = nil
}
